import React from 'react';
import StaticPageLayout from './StaticPageLayout';

const TermsOfService = (props) => {
  return (
    <StaticPageLayout title="Terms of Service" {...props}>
      <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '2rem' }}>
        Last updated: August 28, 2026
      </p>

      <p style={{ marginBottom: '1.5rem' }}>
        Please read these Terms of Service carefully before using the Wakalat AI platform.
      </p>

      <h3 style={{ fontSize: '1.5rem', color: '#111827', marginTop: '2.5rem', marginBottom: '1rem', fontWeight: 700 }}>1. Acceptance of Terms</h3>
      <p style={{ marginBottom: '1.5rem' }}>
        By accessing or using Wakalat AI, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
      </p>

      <h3 style={{ fontSize: '1.5rem', color: '#111827', marginTop: '2.5rem', marginBottom: '1rem', fontWeight: 700 }}>2. Legal Advice Disclaimer</h3>
      <p style={{ marginBottom: '1.5rem' }}>
        Wakalat AI is an AI-powered legal research assistant. **It does not provide legal advice.** The platform is designed to assist legal professionals, and any output generated by the AI should be independently verified by a qualified attorney. We are not liable for any damages resulting from reliance on the AI's output.
      </p>

      <h3 style={{ fontSize: '1.5rem', color: '#111827', marginTop: '2.5rem', marginBottom: '1rem', fontWeight: 700 }}>3. User Responsibilities</h3>
      <p style={{ marginBottom: '1.5rem' }}>
        You are responsible for safeguarding your account password and for all activities that occur under your account. You agree not to upload any illegal or prohibited content.
      </p>
    </StaticPageLayout>
  );
};

export default TermsOfService;
